language: generic
sudo : required

services:
  - docker

before_install:
  - docker build -t vishveshyadav/metric -f ./docker/Dockerfile.app
  - docker build -t vishveshyadav/influxdb -f ./docker/Dockerfile.influx
