language: java

services:
  - docker
  - influxdb

before_install:
  - influxd
  - mvn clean install
  - cp ./target/metric-0.0.1-SNAPSHOT.jar ./docker/metric-0.0.1-SNAPSHOT.jar

install:
  - docker build -t vishveshyadav/metric -f ./docker/Dockerfile.app  ./docker
  - docker build -t vishveshyadav/influxdb -f ./docker/Dockerfile.influx ./docker

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push vishveshyadav/metric
  - docker push vishveshyadav/influxdb

branches:
  only:
   - master