server:
  port: 8085

management:
  metrics:
    export:
      influx:
        auto-create-db: true
        db: customdb
        enabled: true
        uri: http://influx-cluster-ip-service:8086  # change the hostname to localhost for running on local env or your docker service name for docker env
        user-admin: THOR
        step: 10s
  endpoints:
    web:
      exposure:
        include: "*"